name: Generate and Upload Doxygen Documentation

on:
  push:
    branches:
      - develop

jobs:
  generate-documentation:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Generate Doxygen Documentation
      uses: mattnotmitt/doxygen-action@v1.9.5
      with:
        enable-latex: true
        working-directory: ${{ github.workspace }}/Doxyfile
        additional-packages: font-fira-code

    - name: Upload PDF Documentation
      uses: actions/upload-artifact@v2
      with:
        name: pdf-artifact
        path: ${{ github.workspace }}/doc/latex/refman.pdf
