name: Generate Doxygen Documentation

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Generate Documentation
      uses: mattnotmitt/doxygen-action@v1.9.5
      with:
        enable-latex: true

    - name: Upload PDF artifact
      uses: actions/upload-artifact@v2
      with:
        name: pdf-artifact
        path: doc/latex/refman.pdf
